### ISSUE TITLE
Example relying on git proper rather than Github

### ISSUE THREAD

**Issue by Utopiah** [coderofsalvation/aframe-verse#2]
I'd be curious to try with a self-hosted Gitea server e.g https://git.benetou.fr/explore/repos

**Comment by coderofsalvation** [comment]
Thanks! 
I've playing with gitea a lot in the beginning of this year, and I'd love a 'pages'-feature..but do far I didn't find one.
You?

**Comment by Utopiah** [comment]
I didn't have that need so far. I'm not coupling git hosting with content hosting but indeed others https://github.com/go-gitea/gitea/issues/302 had discussed that before. I imagine a Webhook https://docs.gitea.io/en-us/webhooks/ would do so that after a commit on a project it get pushed to a Web server.

**Comment by coderofsalvation** [comment]
oh nice in that case it already works!
Thanks for pointing that out.
I guess a similar way of deploying a federated aframe-verse repo can be done using gitlab & github webhooks.
Before closing this issue, let me give a quick example how anyone with a linuxserver could setup the deployment-webhook:

1) Run this script somehow in the background of your server:

```
#/bin/sh
export JOB="cd /dir/to/aframe-verse-webdir && git reset --hard && git pull origin master"
export PORT=9000
socat -t2 TCP4-LISTEN:$PORT,fork,max-children=1,forever,reuseaddr SYSTEM:"$JOB",pty,echo=0;
```

2) test it typing `curl http://yourserver:9000 --http0.9` from your laptop e.g.
3) enter the URL `http://yourserver:9000` into the appropriate webhook-textfield in github/gitlab/gitea

ps. I'm closing this issue, but anyone is free to comment other examples
